- project:
    templates:
      - openstack-python35-jobs-nonvoting
      - check-requirements
    check:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py27
    gate:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py27
